export const FETCH_PHOTOGRAPHERS_BEGIN  = 'FETCH_PHOTOGRAPHERS_BEGIN';
export const FETCH_PHOTOGRAPHERS_SUCCESS = 'FETCH_PHOTOGRAPHERS_SUCCESS';
export const SET_CURRENT_PHOTOGRAPHER = "SET_CURRENT_PHOTOGRAPHER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATED_USER = "AUTHENTICATING_USER";
export const FAILED_LOGIN = "FAILED_LOGIN";
