export const FETCH_PHOTOGRAPHERS_BEGIN  = 'FETCH_PHOTOGRAPHERS_BEGIN';
export const FETCH_PHOTOGRAPHERS_SUCCESS = 'FETCH_PHOTOGRAPHERS_SUCCESS';
export const SET_CURRENT_PHOTOGRAPHER = "SET_CURRENT_PHOTOGRAPHER";
